[package]
name = "peaky"
version = "0.1.0"
authors = ["thomasprocopio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5"
repng = "0.2.2"
pixel-canvas = "0.2.1"
